### ISSUE TITLE
psutil example exits with module not found when using _memimporter

### ISSUE THREAD

**Issue by rkbennett** [desty2k/paker#2]
I pulled latest releases zip file, ran python setup.py build and attempted to run the psutil example with the compiled pyd. This resulted in the following error:
`DEBUG:jsonimporter:searching for psutil
DEBUG:jsonimporter:searching for pwd
DEBUG:jsonimporter:searching for psutil._common
INFO:jsonimporter:psutil._common has been imported successfully
DEBUG:jsonimporter:searching for psutil._compat
INFO:jsonimporter:psutil._compat has been imported successfully
DEBUG:jsonimporter:searching for psutil._pswindows
DEBUG:jsonimporter:searching for psutil._psutil_windows
DEBUG:jsonimporter:searching for psutil._psutil_windows
INFO:jsonimporter:using _memimporter to load '.pyd' file
INFO:jsonimporter:unloaded all modules
Traceback (most recent call last):
  File "c:\Users\User\Desktop\paker-0.7.1\paker-0.7.1\build\lib.win-amd64-cpython-310\psutil_example.py", line 20, in <module>
    import psutil
  File "c:\Users\User\Desktop\paker-0.7.1\paker-0.7.1\build\lib.win-amd64-cpython-310\paker\importers\jsonimporter.py", line 115, in load_module
    exec(jsonmod["code"], mod.__dict__)
  File "<string>", line 107, in <module>
  File "c:\Users\User\Desktop\paker-0.7.1\paker-0.7.1\build\lib.win-amd64-cpython-310\paker\importers\jsonimporter.py", line 115, in load_module
    exec(jsonmod["code"], mod.__dict__)
  File "<string>", line 35, in <module>
  File "c:\Users\User\Desktop\paker-0.7.1\paker-0.7.1\build\lib.win-amd64-cpython-310\paker\importers\jsonimporter.py", line 134, in load_module
    mod = _memimporter.import_module(fullname, path, initname, self._get_data, spec)
ImportError: MemoryLoadLibrary failed loading psutil\_psutil_windows.pyd: The specified module could not be found. (126)
`

Is this an issue with how I compiled memimporter, or something else?

**Comment by rkbennett** [comment]
Disregard, had to do with an incompatible version of psutil from the example, however, using paker dump does have an issue, explicitly with psutil, as psutil doesn't load all the provided py scripts if you pip install, they are only loaded if the system attributes are matched (such as _psutil_aix). I did do a quick and dirty tweak to the __init__ code in the _dump function. Essentially forced an import of the module with `exec(f'import {module.__name__}')` before the for loop, and then verified the submodule was imported before it would be passed to importlib.import_module()
```if module_name in dir(eval(module.__name__)):
                    full_module = importlib.import_module(full_name)```
and then unloaded the module once it was done looping `exec(f"del {module.__name__}")`. Not sure if that is useful to anyone, but it's what I ran into.
